case statement = "switch", "(", expression, ")", "{", { case }+, [default case], "}";

case = "case", constant expression, ":", { statement }*(";"), ["break;"] ;

default case = "default:", { statement }*(";") ;