function decl. = "function", identifier, "(", parameter declarations, "):", $ type name, ";" block, ";" ;

block = declaration part, statement part ;

stmt. part = "begin", { statement }+(";"), "end" ;