single digit = "0" | ".." | "9" ;

digits = {single digit}+;

sign = "+" | "-" ;

(*number = [ sign ], unsigned real | unsigned integer ;*)

whole number = [ sign ] , digits;

real number = [ sign ] , digits [".", digits] ;

single char. = 'any character except \, " or a new line' | "\n" | '\"' |  "\%" | "\\" ;

character = "'", single character, "'" ;

character string = '"', { single character }*, '"' ;