program = {header include}*, main function ;

header include = "#include", "<" | '"', library name, ">" | '"' ;

main function = "int main()", block ;

block = "{", {statement, ";"}*, "}" ;

library name = filename ;