integer literal = whole number;

long long literal = whole number, 'l' | 'L';

float literal = real number , "f" | "F" ;

double literal = real number ;

char literal = "'", single character, "'" ;

c-string literal = '"', { single character }*, '"'  ;
