procedure decl. = "procedure", identifier, "();", block, ";" ;

block = declaration part, statement part ;

decl. part = { variable declarations   }* ;

variable decls. = "var", { variable declaration }+ ;

variable decl. = {identifier}+(","), ":", type name, [ "=", expression ], ";";

stmt. part = "begin", { statement }+(";"), "end" ;