type decls. = "type", { type declaration }+(";") ;

type decl. = type name, "=", alias type name | array type declaration | enum declaration | record declaration | pointer declaration ;

pointer decl. = "^", type name ;

