struct decl. = "struct", [ struct name ], "{", field list, "}", typedef name;

field list = { field declaration }+(";") ;

field decl. = type name, field name, {"[", expression, "]"}* ;

struct name = identifier ;

field name = identifier ;

typedef name = identifier ;