program = {header include}*, declarations, main function ;

header include = "#include", "<" | '"', library name, ">" | '"' ;

declarations = { procedure declaration }* ;

main function = "int main()", block ;

block = "{", {statement, ";"}*, "}" ;

library name = filename ;