procedure decl. = "procedure", identifier, "(", parameter declarations, ");", block, ";" ;

parameter decls. = {parameter declaration}+(";") ;

parameter decl. =  ~ | "const" | "out" | "var", {identifier}+(","), ":", type name;

block = declaration part, statement part ;

decl. part = { variable declarations   }+ ;

variable decls. = "var", { variable declaration }+ ;

variable decl. = {identifier}+(","), ":", type name, [ "=", expression ], ";";

stmt. part = "begin", { statement }+(";"), "end" ;