prototype decl. = type name, function name | procedure name , "(", parameter list ,")", ";" ;

parameter list = { parameter declaration }* ;

parameter decl. = type name, [ "*" ], parameter name, {"[","]"}* ;

function name = identifier ;

procedure name = identifier ;

type name = identifier ;

param. name = identifier ;
